site_name: Numpydoclint
site_description: Linter for Numpy style docstrings.
site_url: https://nickuzmenkov.github.io/numpydoclint/
repo_name: numpydoclint
repo_url: https://github.com/nickuzmenkov/numpydoclint
edit_uri: ""
nav:
  - 'index.md'
  - 'quickstart.md'
  - 'complete_reference.md'
  - 'release_notes.md'
theme:
  name: 'material'
  palette:
  - scheme: 'default'
    media: '(prefers-color-scheme: light)'
    primary: 'black'
    toggle:
      icon: 'material/lightbulb-outline'
      name: "Switch to dark mode"
  - scheme: 'slate'
    media: '(prefers-color-scheme: dark)'
    primary: 'black'
    toggle:
      icon: 'material/lightbulb'
      name: 'Switch to light mode'
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.code.select
plugins:
  - search
  - termynal
markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
